### ISSUE TITLE
wip

### ISSUE THREAD

**Issue by abraini-Nascent** [PatoSalazarNascent/aimiles-api-cli#1]
when I type in `(wip)` I get `-bash: wip: command not found`

**Comment by PatoSalazarNascent** [comment]
Get a life NErd

**Comment by soliveira-nascent** [comment]
I'm getting the same issue. When will this be fixed?

**Comment by PatoSalazarNascent** [comment]
@soliveira-nascent let's go for some porkettas to discuss this issue
