### ISSUE TITLE
What do I do with .vscode folder?

### ISSUE THREAD

**Issue by soliveira-nascent** [PatoSalazarNascent/aimiles-api-cli#2]
Do I need this to run the CLI tool? I don't use VSCode

**Comment by PatoSalazarNascent** [comment]
No... I like to point our users to superior IDE
Enjoy! 
[VSCode Link](https://code.visualstudio.com/)

**Comment by PatoSalazarNascent** [comment]
BTW I just removed it and added it to the git ignore..
